# cannot update to go113 because of https://stackoverflow.com/questions/56249339/what-is-the-correct-context-for-appengine-taskqueue-in-go112-standard-runtime
runtime: go111

handlers:
- url: /.*
  secure: always
  script: auto
